### ISSUE TITLE
pip install missing dependencies

### ISSUE THREAD

**Issue by jeremyfowers** [intel/intel-extension-for-transformers#1365]
When I use `pip install intel-extension-for-transformers` in a fresh conda environment, there are some packages missing that I have to manually install before I can run a model.

Please add these to setup.py as deps!
- accelerate
- neural-speed
- gguf
- there may be others, I installed some other things before I started writing these down

To reproduce, simply:
- `conda create -n itrex python=3.9`
- `pip install intel-extension-for-transformers`
- Run the following 3-line python script:

```python
from intel_extension_for_transformers.transformers import AutoModelForCausalLM

model_name = "meta-llama/Llama-2-7b-hf"

model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
```

**Comment by kta-intel** [comment]
Hi, thanks for bringing this up and for the suggestion! We'll look into adding the packages you listed as well as whatever other ones are missing

**Comment by kta-intel** [comment]
Following up. After some discussion, we figured it is better to better highlight the required packages per feature and include them as a requirements.txt (or within the instructions). Since this extension has a variety of features, it would be too bloated to include them all during installation. For example, neural-speed is only required to use the neural-speed backend, but is otherwise optional. We will make this more clear in the documentation

**Comment by jeremyfowers** [comment]
Thanks! That sounds good to me and will save time :)
