### ISSUE TITLE
Requirements.txt underscores instead of dashes

### ISSUE THREAD

**Issue by anthony-intel** [intel/intel-extension-for-transformers#1421]
https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/requirements.txt

Uses underscores `intel_extension_for_pytorch`
but it should be dashes? 

Not found (in red) 
![image](https://github.com/intel/intel-extension-for-transformers/assets/160781210/76d9ec97-a293-4cbf-b703-e0deb42baaff)

Edit: removed reference to other library

**Comment by kevinintel** [comment]
Different projects

**Comment by anthony-intel** [comment]
Here's a screenshot of install instructions for the other library, its showing as dashes.

Yes they are different, but issues appears to remain
________________________________

**Comment by anthony-intel** [comment]
![Uploading Screenshot_20240326_080309_Edge.jpg…]()

**Comment by kevinintel** [comment]
It would not a problem, please try tagain
<img width="1391" alt="image" src="https://github.com/intel/intel-extension-for-transformers/assets/93257626/a45a43d0-b3cc-4fcf-9445-2354b5d51538">

**Comment by anthony-intel** [comment]
Could be related to python version. Appears 3.12 is not supported.
Added to this existing ticket on other repo 
https://github.com/intel/intel-extension-for-pytorch/issues/525#issuecomment-2023251003

FYI it's showing as dashes here so not sure why this is being treated differently for this context
https://pypi.org/project/intel-extension-for-pytorch/

**Comment by VincyZhang** [comment]
@anthony-intel  Thanks for sharing! Actually `intel_extension_for_pytorch` package supports both `intel_extension_for_pytorch` and `intel-extension-for-pytorch` on PyPI (not only IPEX, but also ITREX and other similar named projects). What you found here https://pypi.org/project/intel-extension-for-pytorch/ is because Pypi will replace `_` with `-`, but eventually they are the same product.
Let's keep tracking here https://github.com/intel/intel-extension-for-pytorch/issues/525#issuecomment-2023251003
If it's okay for you, please close the ticket in ITREX.

**Comment by anthony-intel** [comment]
Thanks for update!
