### ISSUE TITLE
Support batch inference for chatglm/chatglm2?

### ISSUE THREAD

**Issue by Lzhang-hub** [intel/intel-extension-for-transformers#527]
Is this runtime support batch inference for chatglm or chatglm2?

**Comment by kevinintel** [comment]
we will support it next month

**Comment by zhentaoyu** [comment]
Hi, @Lzhang-hub , thanks for your question! We will support static batch inference which will benefit `beam search` and batch outputs of `top_p-top_k`  for ChatGLM models first in the next month (or by the end of 2023) due to other high-priority features. Continuous batching is still on the plan, will let you know after we make any progress on it. Thanks.

**Comment by zhentaoyu** [comment]
Hi, @Lzhang-hub. The latest ITREX (#700) has supported the `chatglm` static batching infer (padding-left) with `greedy search`. You can have a try, thanks.

**Comment by Lzhang-hub** [comment]
Greate work! I will try it.

**Comment by kevinintel** [comment]
Hi @Lzhang-hub,
I will close this issue if you don't have concerns.
