### ISSUE TITLE
Unable to build the graph due to error with avx512bf16 compilation

### ISSUE THREAD

**Issue by amir1m** [intel/intel-extension-for-transformers#726]
Hello,

I am trying to build the graph. I followed the steps from [README](https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/llm/runtime/graph) . After `cmake .. -G Ninja` , when I run `ninja` , getting following error:

```
/home/datascience/intel-extension-for-transformers/intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h:24:32: error: attribute(target("avx512bf16")) is unknown
#pragma GCC target("avx512bf16")

```
Even tried disabling AVX 512 as, `cmake -G Ninja -DNE_AVX512=OFF -DNE_AVX512_VBMI=OFF -DNE_AVX512_VNNI=OFF` , still the same results.

I am running Linux on Intel(R) Xeon(R) Platinum 8167M CPU @ 2.00GHz

Can someone please help?

Thanks.

**Comment by zhewang1-intc** [comment]
Thank you for your feedback. This is a known issue caused by that older versions of the gcc compiler (gcc version <11)  not support avx512bf16 compile option. This issue has been fixed in https://github.com/intel/intel-extension-for-transformers/pull/707, so please update the main branch or upgrade your compiler version and try again. 
By the way, if you want to use the bf16-related features of the itrex backend, it is best to upgrade the gcc version to 11 or above. If you want to use the fp16-related features, you must upgrade the gcc version to 13.

**Comment by amir1m** [comment]
Thanks @zhewang1-intc for your response! After upgrading to GCC 12 it worked as expected. Since GCC
