### ISSUE TITLE
Installation is broken for python3.11

### ISSUE THREAD

**Issue by ei-grad** [intel/intel-extension-for-transformers#760]
ModuleNotFoundError: No module named 'cmake'
      ModuleNotFoundError: No module named 'cpuinfo'

**Comment by NeoZhangJianyu** [comment]
@ei-grad 
Could you share the cmd to install ITREX?
It's great if you could provide the whole log with this error.

**Comment by airMeng** [comment]
https://stackoverflow.com/questions/58992376/no-module-named-cmake
Hi @ei-grad can you check cmake as the link above?

**Comment by DDEle** [comment]
It is a known problem that we cannot specify required version of torch for wheel-building so that build-time requirements must be installed manually when build from source (including the sdist).
 
To install the build-time requirements, try running `pip install -r https://raw.githubusercontent.com/intel/intel-extension-for-transformers/main/requirements.txt` beforehand.
 
(And then windows will complain about the long path problem in my experience). In that case, you have to build from source (in a directory with short name). e.g.:
```batch
cd "c:\"
git clone https://github.com/intel/intel-extension-for-transformers.git itrex
cd itrex
pip install -r requirements.txt
pip install -v .
```

**Comment by kevinintel** [comment]
Hi, I will close this issue if you don't have concerns
