### ISSUE TITLE
Unable to run example of stable_diffusion

### ISSUE THREAD

**Issue by yujiepan-work** [intel/intel-extension-for-transformers#78]
In `examples/huggingface/pytorch/text-to-image/deployment/stable_diffusion/README.md`, "End-to-End Workflow" section:
- Download Models: OK
- Compile Models: `TypeError: expected str, bytes or os.PathLike object, not dict`
![image](https://github.com/intel/intel-extension-for-transformers/assets/105195712/eff56b54-108c-4847-bf7f-3bedf9be4886)

after fixing this: `AttributeError: 'NoneType' object has no attribute 'get'`
![image](https://github.com/intel/intel-extension-for-transformers/assets/105195712/f5987b05-e619-483a-a131-6f80de705a36)

- Performance check: `KeyError: '/text_model/Gather_1_output_0:0'`
![image](https://github.com/intel/intel-extension-for-transformers/assets/105195712/691e3f1e-6135-4633-88d8-8284efcaca04)

version：
- torch==2.0.0+cpu
- intel-extension-for-transformers ==1.0.1

**Comment by Zhenzhong1** [comment]
Hi, it looks like you installed the ITREX wheel package and then ran this latest Repo stable diffusion example. It may have some problems, because the Repo code is the latest, it will not be compatible with some previous issues.

1. Please install the ITREX from the source code.
2. Please install transformers==4.28.1 manually.
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/283a9a9d-4801-4231-ab28-52d875d0d11d)

3. Rerun the steps to prepare the model and compile the model:
`python prepare_model.py --input_model=CompVis/stable-diffusion-v1-4 --output_path=./model --bf16`
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/b98f1a5e-0ade-4fa4-85d2-19ed4dd1556a)


`bash export_model.sh --input_model=model --precision=bf16`
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/18e09f61-245a-47ec-b3c9-789fd8a10807)

`python run_executor.py --ir_path=./bf16_ir --mode=latency --input_model=CompVis/stable-diffusion-v1-4`
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/18503647-87f1-4fc5-84d0-5f413f7552b8)

**Comment by yujiepan-work** [comment]
Thanks for your reply.  I have been able to run the example.
