### ISSUE TITLE
unable to install intel_extension_for_pytorch - Windows 10

### ISSUE THREAD

**Issue by hanikhatib** [intel/intel-extension-for-transformers#785]
Is there a workaround for this? Does anyone know if this module will be available for Windows OS anytime soon?

**Comment by VincyZhang** [comment]
Hi @hanikhatib, we have the same issue installing intel_extension_for_pytorch (IPEX) on Windows, that's why we do not support any IPEX related features on windows right now. 
I think it would be better if you submit an issue to [IPEX Issues](https://github.com/intel/intel-extension-for-pytorch/issues), see if they have plan to support Windows again in the future.
